from enum import Enum

from static_site_generator import util
from typing import Optional


class HtmlAttribute(object):
    class _Attrbute(Enum):
        ACCEPT = "accept"
        ACCESSKEY = "accesskey"
        ACTION = "action"
        ALIGN = "align"
        ALT = "alt"
        ASYNC = "async"
        AUTOCOMPLETE = "autocomplete"
        AUTOFOCUS = "autofocus"
        AUTOPLAY = "autoplay"
        BGCOLOR = "bgcolor"
        BORDER = "border"
        CHARSET = "charset"
        CHECKED = "checked"
        CITE = "cite"
        CLASS_ = "class"
        COLOR = "color"
        COLS = "cols"
        COLSPAN = "colspan"
        CONTENT = "content"
        CONTENTEDITABLE = "contenteditable"
        CONTROLS = "controls"
        COORDS = "coords"
        DATA = "data"
        DATETIME = "datetime"
        DEFAULT = "default"
        DEFER = "defer"
        DIR = "dir"
        DIRNAME = "dirname"
        DISABLED = "disabled"
        DOWNLOAD = "download"
        DRAGGABLE = "draggable"
        ENCTYPE = "enctype"
        ENTERKEYHINT = "enterkeyhint"
        FOR = "for"
        FORM = "form"
        FORMACTION = "formaction"
        HEADERS = "headers"
        HEIGHT = "height"
        HIDDEN = "hidden"
        HIGH = "high"
        HREF = "href"
        HREFLANG = "hreflang"
        HTTP = "http"
        ID = "id"
        INERT = "inert"
        INPUTMODE = "inputmode"
        ISMAP = "ismap"
        KIND = "kind"
        LABEL = "label"
        LANG = "lang"
        LIST_ = "list"
        LOOP = "loop"
        LOW = "low"
        MAX = "max"
        MAXLENGTH = "maxlength"
        MEDIA = "media"
        METHOD = "method"
        MIN = "min"
        MULTIPLE = "multiple"
        MUTED = "muted"
        NAME = "name"
        NOVALIDATE = "novalidate"
        ONABORT = "onabort"
        ONAFTERPRINT = "onafterprint"
        ONBEFOREPRINT = "onbeforeprint"
        ONBEFOREUNLOAD = "onbeforeunload"
        ONBLUR = "onblur"
        ONCANPLAY = "oncanplay"
        ONCANPLAYTHROUGH = "oncanplaythrough"
        ONCHANGE = "onchange"
        ONCLICK = "onclick"
        ONCONTEXTMENU = "oncontextmenu"
        ONCOPY = "oncopy"
        ONCUECHANGE = "oncuechange"
        ONCUT = "oncut"
        ONDBLCLICK = "ondblclick"
        ONDRAG = "ondrag"
        ONDRAGEND = "ondragend"
        ONDRAGENTER = "ondragenter"
        ONDRAGLEAVE = "ondragleave"
        ONDRAGOVER = "ondragover"
        ONDRAGSTART = "ondragstart"
        ONDROP = "ondrop"
        ONDURATIONCHANGE = "ondurationchange"
        ONEMPTIED = "onemptied"
        ONENDED = "onended"
        ONERROR = "onerror"
        ONFOCUS = "onfocus"
        ONHASHCHANGE = "onhashchange"
        ONINPUT = "oninput"
        ONINVALID = "oninvalid"
        ONKEYDOWN = "onkeydown"
        ONKEYPRESS = "onkeypress"
        ONKEYUP = "onkeyup"
        ONLOAD = "onload"
        ONLOADEDDATA = "onloadeddata"
        ONLOADEDMETADATA = "onloadedmetadata"
        ONLOADSTART = "onloadstart"
        ONMOUSEDOWN = "onmousedown"
        ONMOUSEMOVE = "onmousemove"
        ONMOUSEOUT = "onmouseout"
        ONMOUSEOVER = "onmouseover"
        ONMOUSEUP = "onmouseup"
        ONMOUSEWHEEL = "onmousewheel"
        ONOFFLINE = "onoffline"
        ONONLINE = "ononline"
        ONPAGEHIDE = "onpagehide"
        ONPAGESHOW = "onpageshow"
        ONPASTE = "onpaste"
        ONPAUSE = "onpause"
        ONPLAY = "onplay"
        ONPLAYING = "onplaying"
        ONPOPSTATE = "onpopstate"
        ONPROGRESS = "onprogress"
        ONRATECHANGE = "onratechange"
        ONRESET = "onreset"
        ONRESIZE = "onresize"
        ONSCROLL = "onscroll"
        ONSEARCH = "onsearch"
        ONSEEKED = "onseeked"
        ONSEEKING = "onseeking"
        ONSELECT = "onselect"
        ONSTALLED = "onstalled"
        ONSTORAGE = "onstorage"
        ONSUBMIT = "onsubmit"
        ONSUSPEND = "onsuspend"
        ONTIMEUPDATE = "ontimeupdate"
        ONTOGGLE = "ontoggle"
        ONUNLOAD = "onunload"
        ONVOLUMECHANGE = "onvolumechange"
        ONWAITING = "onwaiting"
        ONWHEEL = "onwheel"
        OPEN = "open"
        OPTIMUM = "optimum"
        PATTERN = "pattern"
        PLACEHOLDER = "placeholder"
        POPOVER = "popover"
        POPOVERTARGET = "popovertarget"
        POPOVERTARGETACTION = "popovertargetaction"
        POSTER = "poster"
        PRELOAD = "preload"
        READONLY = "readonly"
        REL = "rel"
        REQUIRED = "required"
        REVERSED = "reversed"
        ROWS = "rows"
        ROWSPAN = "rowspan"
        SANDBOX = "sandbox"
        SCOPE = "scope"
        SELECTED = "selected"
        SHAPE = "shape"
        SIZE = "size"
        SIZES = "sizes"
        SPAN = "span"
        SPELLCHECK = "spellcheck"
        SRC = "src"
        SRCDOC = "srcdoc"
        SRCLANG = "srclang"
        SRCSET = "srcset"
        START = "start"
        STEP = "step"
        STYLE = "style"
        TABINDEX = "tabindex"
        TARGET = "target"
        TITLE = "title"
        TRANSLATE = "translate"
        TYPE_ = "type"
        USEMAP = "usemap"
        VALUE = "value"
        WIDTH = "width"
        WRAP = "wrap"
        _INVALID_ATTR = "INVALID_ATTRIBUTE"

    _attr_set = util.enum_values(_Attrbute)

    @classmethod
    def is_attr(cls, s: str) -> bool:
        s in cls._attr_set

    @classmethod
    def fmt_attr(cls, key: str, value: str) -> Optional[str]:
        """
        Html attribute string for `attr`.

        Parameters
        ----------
        key : html attribute
        value : attribute value

        Returns
        ----------
        attr : html attribute string if `key` is not a valid html attribute, otherwise `None`
        """
        if cls.is_attr(key):
            attr = f"{key}={value} "
        else:
            attr = None
        return attr
